global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Your inference server (if it exposes metrics)
  - job_name: 'inference-server'
    static_configs:
      - targets: ['inference-server:6061']

  - job_name: 'raspberry-pi'
    static_configs:
      - targets: ['192.168.178.26:9100']
